### ISSUE TITLE
Error: Cannot find module 'node:buffer' によって起動できない問題

### ISSUE THREAD

**Issue by Atria64** [fun-developers-hub/fdh-frontend#22]
おま環かもしれませんが遭遇したのでIssueにしておきます。
   
## 概要
 - 62c8e27 (main)
 - `npm run dev` で起動できない
## エラーログ
``` sh
npm run dev

> fdh-frontend@0.1.0 dev C:\Users\daich\source\fdh-frontend
> next dev

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:buffer'
Require stack:
- C:\Users\daich\source\fdh-frontend\node_modules\next\dist\server\web\sandbox\context.js
- C:\Users\daich\source\fdh-frontend\node_modules\next\dist\server\web\sandbox\sandbox.js
- C:\Users\daich\source\fdh-frontend\node_modules\next\dist\server\web\sandbox\index.js
- C:\Users\daich\source\fdh-frontend\node_modules\next\dist\build\utils.js
- C:\Users\daich\source\fdh-frontend\node_modules\next\dist\build\worker.js
- C:\Users\daich\source\fdh-frontend\node_modules\next\dist\cli\next-dev.js
- C:\Users\daich\source\fdh-frontend\node_modules\next\dist\lib\commands.js
- C:\Users\daich\source\fdh-frontend\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\daich\source\fdh-frontend\node_modules\next\dist\server\web\sandbox\context.js:28:60)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\daich\\source\\fdh-frontend\\node_modules\\next\\dist\\server\\web\\sandbox\\context.js',
    'C:\\Users\\daich\\source\\fdh-frontend\\node_modules\\next\\dist\\server\\web\\sandbox\\sandbox.js',
    'C:\\Users\\daich\\source\\fdh-frontend\\node_modules\\next\\dist\\server\\web\\sandbox\\index.js',
    'C:\\Users\\daich\\source\\fdh-frontend\\node_modules\\next\\dist\\build\\utils.js',
    'C:\\Users\\daich\\source\\fdh-frontend\\node_modules\\next\\dist\\build\\worker.js',
    'C:\\Users\\daich\\source\\fdh-frontend\\node_modules\\next\\dist\\cli\\next-dev.js',
    'C:\\Users\\daich\\source\\fdh-frontend\\node_modules\\next\\dist\\lib\\commands.js',
    'C:\\Users\\daich\\source\\fdh-frontend\\node_modules\\next\\dist\\bin\\next'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fdh-frontend@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fdh-frontend@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daich\AppData\Roaming\npm-cache\_logs\2023-06-21T05_33_47_511Z-debug.log
```

#### complete log
```sh
PS C:\Users\daich\source\fdh-frontend> cat C:\Users\daich\AppData\Roaming\npm-cache\_logs\2023-06-21T05_33_47_511Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle fdh-frontend@0.1.0~predev: fdh-frontend@0.1.0
6 info lifecycle fdh-frontend@0.1.0~dev: fdh-frontend@0.1.0
7 verbose lifecycle fdh-frontend@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle fdh-frontend@0.1.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\daich\source\fdh-frontend\node_modules\.bin;C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\usbipd-win\;C:\Program Files\dotnet\;C:\Users\daich\AppData\Local\Microsoft\WindowsApps;C:\Users\daich\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\daich\.dotnet\tools;C:\Users\daich\AppData\Local\GitHubDesktop\bin;C:\Users\daich\AppData\Local\Microsoft\WindowsApps;C:\Users\daich\.dotnet\tools;C:\Users\daich\AppData\Roaming\npm;C:\Program Files\heroku\bin
9 verbose lifecycle fdh-frontend@0.1.0~dev: CWD: C:\Users\daich\source\fdh-frontend
10 silly lifecycle fdh-frontend@0.1.0~dev: Args: [ '/d /s /c', 'next dev' ]
11 silly lifecycle fdh-frontend@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle fdh-frontend@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: fdh-frontend@0.1.0 dev: `next dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid fdh-frontend@0.1.0
15 verbose cwd C:\Users\daich\source\fdh-frontend
16 verbose Windows_NT 10.0.25267
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error fdh-frontend@0.1.0 dev: `next dev`
22 error Exit status 1
23 error Failed at the fdh-frontend@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## nodeのバージョン
```
node -v
v14.15.1
```

**Comment by TadaTeruki** [comment]
nodeのバージョンを`v14.15.1`にすると同様のエラーが見られました

新しいバージョンにアップグレードするとうまくいきそうです
（自分の環境（下参照）では問題なく動きました）

```
node -v
v16.18.1
```

どうでしょうか？

**Comment by Atria64** [comment]
v16.18.1にしたら動きました、やっぱり古いバージョンだとダメみたいです!
